[package]
name = "galleon_starknet"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.5.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "81bb93c" }
starknet = "=2.5.0"
